name = "ovitrampas-api"
main = "src/index.js"
compatibility_date = "2026-07-29"

[[d1_databases]]
binding = "DB"
database_name = "ovitrampas-gps-db"
database_id = "7f230c39-789f-416d-95fd-4e22e7fd5d69"
